/*
   Copyright 2020 Google LLC

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

public class Constants {
	
	public static final String OPPORTUNITY_STAGENAME_PROSPECTING = 'Prospecting';
	public static final String OPPORTUNITY_STAGENAME_QUALIFICATION = 'Qualification';
	public static final String OPPORTUNITY_STAGENAME_NEEDS_ANALYSIS = 'Needs Analysis';
	public static final String OPPORTUNITY_STAGENAME_VALUE_PROPOSITION = 'Value Proposition';
	public static final String OPPORTUNITY_STAGENAME_ID_DECISION_MAKERS = 'Id. Decision Makers';
	public static final String OPPORTUNITY_STAGENAME_PERCEPTION_ANALYSIS = 'Perception Analysis';
	public static final String OPPORTUNITY_STAGENAME_PROPOSAL_PRICE_QUOTE = 'Proposal/Price Quote';
	public static final String OPPORTUNITY_STAGENAME_NEGOTIATION_REVIEW = 'Negotiation/Review';
	public static final String OPPORTUNITY_STAGENAME_CLOSED_WON = 'Closed Won';
	public static final String OPPORTUNITY_STAGENAME_CLOSED_LOST = 'Closed Lost';
	
}
