/*
   Copyright 2024 Google LLC

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

	https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/**
 * @description An abstract class that provides a base structure for trigger context records.
 */
global abstract class TriggerRecord {
	/**
	 * @description The new version of the SObject that triggered the current execution context.
	 */
	global SObject newSobject {
		get {
			return newSobject;
		}
		set {
			this.newSobject = value;
		}
	}

	/**
	 * @description The previous version of the SObject that triggered the current execution context.
	 */
	global SObject oldSobject {
		get {
			return oldSobject;
		}
		set {
			this.oldSobject = value;
		}
	}
}
