name: Generate Package Version

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        required: true
        type: string

jobs:
  create-package-version:
    runs-on: ubuntu-latest
    outputs:
      packageId: ${{ steps.create.outputs.packageId }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ">=20"

      - name: Install sf cli
        run: |
          npm install --global @salesforce/cli

      - name: Authenticate into DevHub
        run: |
          echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
          sf org login jwt --client-id ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwt-key-file server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --set-default-dev-hub --alias devhub
        env:
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

      - name: Create package version
        id: create
        run: |
          sf package version create --definition-file config/project-scratch-def.json --package "Trigger Actions Framework" --package-version ${{ inputs.packageVersion }} --tag ${{ github.sha }} --wait 120 --code-coverage --installation-key-bypass --json
